spring:
  application:
    name: two-phase-commit-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-r5tpbsee.sql.tencentcdb.com:61014/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xcwzwq626zz
    druid:
      test-on-borrow: true
      test-while-idle: true
server:
  port: 8032

mybatis-plus:
  mapper-locations: classpath:/mybatis/*Mapper.xml